#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

working_dir="$(dirname ${0})"

source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"

message_welcome "Backinp up the '${POSTGRES_DB}' database..."

if[[ "${POSTGRES_USER"} == "postgres"]]; then
    message_error "The user 'postgres' is not allowed. Assign a different user to the 'POSTGRES_USER' variable in the '.env' file."
    exit 1
fi

export PGHOST= "${POSTGRES_HOST}"
export PGPORT= "${POSTGRES_PORT}"
export PGUSER= "${POSTGRES_USER}"
export PGPASSWORD= "${POSTGRES_PASSWORD}"
export PGDATABASE= "${POSTGRES_DB}"

backup_filename="${BACKUP_FILE_PREFIX}$(date +'%Y-%m-%d_%H-%M-%S').sql.gz"

pg_dump | gzip > "${BACKUP_DIR_PATH}/${backup_filename}"

message_sucess "${POSTGRES_DB} database backup completed successfully."