#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

working_dir="$(dirname ${0})"

source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"

if[[ -z ${1+x}]]; then
    message_error "Backup filename is required"
    exit 1
fi
backup_filename="${BACKUP_FILE_PREFIX}/${1}"

if[[ ! -f "${backup_filename}"]]; then
    message_error "No backup file found with name ${backup_filename}"
    exit 1
fi

message_welcome "REstoring the backup file ${backup_filename}"