#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset

if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user="postgres"
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi

export DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

python << END
import sys
import time
import psycopg2
suggest_unrecoverable_after = 30
start = time.time()
while True:
    try:
        conn = psycopg2.connect(
            dbname="${POSTGRES_DB}",
            user="${POSTGRES_USER}",
            password="${POSTGRES_PASSWORD}",
            host="${POSTGRES_HOST}",
            port="${POSTGRES_PORT}",
        )
        break
    except psycopg2.OperationalError as e:
        sys.strerr.write("Waiting for postgres to be ready...\n")
        if time.time() - start > suggest_unrecoverable_after:
            sys.stderr.write("Postgres took too long to become ready. The following exception was raised: '{}'\n".format(e))
        time.sleep(1)
END

>&2 echo "Postgres is up and running!"

exec "$@"